# Generated by Django 4.2.1 on 2023-05-30 12:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='birth')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.CharField(blank=True, help_text="13 character <a href='https://isbn/'>in this site</a>", max_length=13, null=True, verbose_name='ISBN')),
                ('summery', models.CharField(help_text='enter a brife description of the book', max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author')),
            ],
        ),
        migrations.CreateModel(
            name='Gener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter book gener', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bookinstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('r', 'reserved'), ('m', 'maintenance'), ('a', 'on lone'), ('a', 'available')], default='m', help_text='book status', max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='gener',
            field=models.ManyToManyField(help_text='select gener of this book', to='catalog.gener'),
        ),
    ]
