# Generated by Django 4.2.1 on 2023-06-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrow',
            new_name='borrower',
        ),
    ]
